[colors]
ansi = [
    '#1f1e20',
    '#c05862',
    '#b1b695',
    '#f5d76e',
    '#ffa07a',
    '#f6b6c9',
    '#bfbfcf',
    '#f5f5f5',
]
background = '#2b292d'
brights = [
    '#2b292d',
    '#e06b75',
    '#9f9f7c',
    '#fff27a',
    '#e88c6f',
    '#ffb9cc',
    '#d1d1e0',
    '#ffffff',
]
cursor_bg = '#fecdb2'
cursor_border = '#fecdb2'
cursor_fg = '#383539'
foreground = '#fecdb2'
selection_bg = '#4d424b'
selection_fg = '#fecdb2'

[colors.indexed]

[metadata]
name = 'ferra'
origin_url = 'https://github.com/casperstorm/ferra'
